# Site settings
title: James Chu
email: james@james-chu.com
description: > #
  Passionate about all things digital,
  I am a graphic designer who specializes in branding and user experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http//www.james-chu.com" # the base hostname & protocol for your site

exclude: [node_modules, gulpfile.js, package.json, CNAME]
include: [images, _work, _work/images]

# Build settings
#markdown: kramdown
