# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James Chu
email: james@james-chu.com
description: > #
  Passionate about all things digital,
  I am a graphic designer who specializes in branding and user experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http//www.james-chu.com" # the base hostname & protocol for your site
twitter_username: jamescchu_
github_username:  jamescchu

exclude: [node_modules, gulpfile.js, package.json, CNAME]
include: [images, _work, _work/images]

# Build settings
markdown: kramdown
